### PR TITLE
client.EnsureIndexes() Implementation

### PR DESCRIPTION
**Pull request by smartinov**

### CODE REVIEW

**Comment by smartinov** [comment]
Fixes issue #3

**Comment by michaelfinch** [comment]
Given that mongo has deprecated ensureIndex (it's now an alias to createIndex...see https://docs.mongodb.com/manual/reference/method/db.collection.ensureIndex/), let's rename the method to CreateIndex. Other than that, lgtm!

**Comment by michaelfinch** [comment]
Also, just a heads up, I need to move this repo over to https://github.com/square/mongo-lock. There's an equivalent PR there (https://github.com/square/mongo-lock/pull/1) that you can move this commit to, or you can just update it here and then I'll copy it over. I'll port over the issues and any other things currently missing tomorrow.

**Comment by michaelfinch** [comment]
I've ported these changes over to https://github.com/square/mongo-lock, so I'm going to close this

**Pull request closed without merging**
